name: Build NDS Homebrew

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install devkitPro
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget lsb-release
          wget https://github.com/devkitPro/pacman/releases/download/v6.0.2/devkitpro-pacman.deb
          sudo dpkg -i devkitpro-pacman.deb
          sudo dkp-pacman -Syu --noconfirm
          sudo dkp-pacman -S --noconfirm devkitARM libnds nds-tools

      - name: Set up environment
        run: |
          echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
          echo "DEVKITARM=/opt/devkitpro/devkitARM" >> $GITHUB_ENV
          echo "$DEVKITARM/bin:$PATH" >> $GITHUB_PATH

      - name: Compile NDS Homebrew
        run: make

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: game.nds
          path: ./your_game.nds  # Adjust to your output filename