name: Build NDS Homebrew

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        run: |
          echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
          echo "DEVKITARM=/opt/devkitpro/devkitARM" >> $GITHUB_ENV
          echo "PATH=$DEVKITARM/bin:$PATH" >> $GITHUB_ENV

      - name: Verify tools
        run: |
          echo "=== Compiler ==="
          $DEVKITARM/bin/arm-none-eabi-gcc --version
          echo "=== ndstool ==="
          ndstool 2>&1 | head -n 3  # Muestra solo las primeras líneas

      - name: Build ROM
        run: |
          make -j$(nproc)
          ls -la *.nds  # Verifica que se generó el archivo

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nds-rom
          path: "*.nds"