name: Build NDS Homebrew

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Environment
        run: |
          echo "=== Versiones ==="
          arm-none-eabi-gcc --version
          ndstool --version
          echo "=== PATH ==="
          echo $PATH

      - name: Build NDS ROM
        run: |
          make -j$(nproc)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nds-rom
          path: "*.nds"  # ¡Corrección clave: comillas alrededor del patrón!