name: Build NDS Homebrew

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo dkp-pacman -Syu --noconfirm
          sudo dkp-pacman -S --noconfirm libnds libcalico nds-tools

      - name: Build
        run: |
          make -j$(nproc)

      - uses: actions/upload-artifact@v4
        with:
          name: nds-rom
          path: "*.nds"