name: Build NDS Homebrew

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          make -j$(nproc)
          ndstool --version 
      - uses: actions/upload-artifact@v4
        with:
          name: nds-rom
          path: |
            *.nds
            *.elf