name: Build NDS Homebrew

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest  # Pre-configured with devkitARM + libnds
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check libnds installation
        run: |
          ls /opt/devkitpro/libnds  
          dkp-pacman -Q | grep libnds 
      - name: Compile NDS Homebrew
        run: |
          make  # Assumes you have a Makefile

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: game.nds
          path: ./your_game.nds  # Adjust to your output filename