name: Build NDS Homebrew

on: [push, pull_request]

jobs:
  build:
    # Recommended: Use devkitPro's official Docker image
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest  # Pre-configured with all tools

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Environment
        run: |
          echo "DEVKITPRO = $DEVKITPRO"
          echo "DEVKITARM = $DEVKITARM"
          dkp-pacman -Q | grep -E 'libnds|devkitARM'

      - name: Build NDS Homebrew
        run: |
          make -j$(nproc)  # Build with parallel jobs

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nds-rom
          path: |
            *.nds
            *.elf  # Optional: Include debug files