name: Build NDS Homebrew

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          # Configura las variables esenciales
          echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
          echo "DEVKITARM=/opt/devkitpro/devkitARM" >> $GITHUB_ENV
          echo "PATH=$DEVKITARM/bin:$PATH" >> $GITHUB_ENV

      - name: Verify tools
        run: |
          echo "=== Herramientas ==="
          ls -la $DEVKITARM/bin/arm-none-eabi-gcc  # Verifica que el compilador existe
          $DEVKITARM/bin/arm-none-eabi-gcc --version
          ndstool --version

      - name: Build
        run: |
          make -j$(nproc)

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: nds-rom
          path: "*.nds"